
# -- URL --
make_trade: '/trades'
get_cash_balance: '/portfolio/cashBalance' #todo improve or remove

# -- HTTP METHOD --
http_method: 'POST' #todo improve or remove

# -- ENVIRONMENT --
development: 'dev'
beta: 'beta'
production: ''

# -- PATH --
version: '3'